version: "3.8"
services:
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    command: [--auth]
    restart: unless-stopped

  api:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    ports:
      - 8080:3000
    command: "npm start"
    depends_on: [mongodb]
    restart: unless-stopped