version: "3.8"
services:
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    command: [--auth]
    restart: unless-stopped

  api:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
#      - DB_USERNAME=<username>
#      - DB_PWD=<password>
#      - DB_IP=mongodb
#      - DB_PORT=27017
#      - API_INTERNAL_PORT=3000
#      - TOKEN_SECRET=<jwt_token_secret>
    volumes:
      - ./api:/home/node/app
    ports:
      - 8080:3000
    command: "npm start"
    depends_on: [mongodb]
    restart: unless-stopped
